name: Build and Deploy Staging to Heroku

on:
  push:
    branches:
      - staging

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Heroku Container Registry
      run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Set Build-Time Environment Variable (NPM_TOKEN)
      run: |
        echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> .env
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build Docker Image
      run: docker build --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_STAGING }}/web .

    - name: Push Docker Image to Heroku
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_STAGING }}/web

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Release to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME_STAGING: ${{ secrets.HEROKU_APP_NAME_STAGING }}
      run: heroku container:release web --app $HEROKU_APP_NAME_STAGING
